#!/bin/bash

# validate claims
# this is an example of how to validate claims from the bundle
#
# usage: validate-claims.sh <bundle>
#
# bundle: path to bundle file
#
# in this case, we want to ALWAYS make sure we fail anything that was generated by an
# ssh rerun, so we will check the OID 1.3.6.1.4.1.57264.1.11 for the value "ssh-rerun"
# for more information, read up the OIDs in fulcio docs

if [ "$#" -ne 1 ]; then
    echo "Usage: validate-claims.sh <bundle>"
    exit 1
fi

bundle="$1"

RUNNER_ENVIRONMENT=$(cat "$bundle" \
  | jq -r '.verificationMaterial.certificate.rawBytes' \
  | base64 -d \
  | step certificate inspect --format json \
  | jq -r '.unknown_extensions[] | select(.id == "1.3.6.1.4.1.57264.1.11") | .value' \
  | base64 -d \
  | tr -dc '[:print:]')

if [ "$RUNNER_ENVIRONMENT" == "ssh-rerun" ]; then
  echo "Error: Runner environment is ssh-rerun - artifact not trusted"
  exit 1
fi